[package]
name = "sleigh_preprocessor"
version = "0.1.0"
authors = ["saruman9 <rum.274.4@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.3"
lazy_static = "1.1"
